# adacursesw-config
# Autogenerated from man page /usr/local/share/man/man1/adacursesw-config.1
# using Deroffing man parser
complete -c adacursesw-config -l cflags --description 'echos the gnat (Ada compiler) flags needed to c… [See Man Page]'
complete -c adacursesw-config -l libs --description 'echos the gnat libraries needed to link with AdaCurses.'
complete -c adacursesw-config -l version --description 'echos the release+patchdate version of the ncur… [See Man Page]'
complete -c adacursesw-config -l help --description 'prints a list of the adacurses-config script\'s options.'

