# adacurses
# Autogenerated from man page /usr/local/share/man/man1/adacurses.1
# using Deroffing man parser
complete -c adacurses -l cflags --description 'echos the gnat (Ada compiler) flags needed to c… [See Man Page]'
complete -c adacurses -l libs --description 'echos the gnat libraries needed to link with AdaCurses.'
complete -c adacurses -l version --description 'echos the release+patchdate version of the ncur… [See Man Page]'
complete -c adacurses -l help --description 'prints a list of the adacurses-config script\'s options.'

