# axauthorize
# Autogenerated from man page /usr/share/man/man1/axauthorize.1
# using Darwin man parser
complete -c axauthorize -s p --description 'Path to the binary or bundle to allow/deny authorization.'
complete -c axauthorize -s s --description 'authStatus specifices if the application should… [See Man Page]'

