# cn
# Autogenerated from man page /usr/share/man/man1/cn.1
# using Darwin man parser
complete -c cn -s h --description 'Show help information.'
complete -c cn -s a --description 'Use the specified algorithm.'
complete -c cn -s s --description 'Performs the operation on the specified string value.'
complete -c cn -s v --description 'Function in Verbose mode.'

