# contacts
# Autogenerated from man page /usr/local/share/man/man1/contacts.1.gz
# using Darwin man parser
complete -c contacts -s h --description 'displays help/usage.'
complete -c contacts -s H --description 'suppresses headers from being displayed.'
complete -c contacts -s s --description 'sorts the list before displaying it.'
complete -c contacts -s m --description 'show the person marked as "me".'
complete -c contacts -s n --description 'displays note below each record (by default onl… [See Man Page]'
complete -c contacts -s l --description 'loose formatting - doesn\'t truncate the record … [See Man Page]'
complete -c contacts -s S --description 'strict formatting - doesn\'t add space between the columns.'
complete -c contacts -s c --description 'output as calendar(1) file format.'
complete -c contacts -s f --description 'accepts a format string (see below) \\" Ends the… [See Man Page]'

