# corelist5
# Autogenerated from man page /usr/share/man/man1/corelist5.16.1
# using Type1
complete -c corelist5 -l diff --description 'Given two versions of perl, this prints a human… [See Man Page]'
complete -c corelist5 -s v --description 'lists all of the perl release versions we got the CoreList for.'

