# hmac256
# Autogenerated from man page /usr/local/share/man/man1/hmac256.1
# using Deroffing man parser
complete -c hmac256 -l binary --description 'Print the MAC as a binary string.'
complete -c hmac256 -l version --description 'Print version of the program and exit.  SEE ALSO sha256sum(1).'

