# htop
# Autogenerated from man page /usr/local/share/man/man1/htop.1
# using Deroffing man parser
complete -c htop -s d --description 'Delay between updates, in tenths of seconds.'
complete -c htop -s u --description 'Show only processes of a given user.'
complete -c htop -l sort-key --description 'Sort by this column (use --sort-key help for a … [See Man Page]'

