# irssi
# Autogenerated from man page /usr/local/share/man/man1/irssi.1
# using Deroffing man parser
complete -c irssi -l config --description 'use   FILE instead of ~/. irssi/config.'
complete -c irssi -l home --description 'PATH  specifies the home directory of Irssi.  Default is   ~/.'
complete -c irssi -s c -l connect --description 'connects to   SERVER.'
complete -c irssi -s w -l password --description 'use  PASSWORD  for authentication.'
complete -c irssi -s p -l port --description 'automatically connect to   PORT  on server.'
complete -c irssi -s '!' -l noconnect --description 'disables autoconnecting.'
complete -c irssi -s n -l nick --description 'specify   NICKNAME  as your nick.'
complete -c irssi -s h -l hostname --description 'use  HOSTNAME for your irc session.'
complete -c irssi -s d -l dummy --description 'use dummy terminal mode.'
complete -c irssi -s v -l version --description 'display the version of Irssi.'
complete -c irssi -s '?' -l help --description 'show a help message.'
complete -c irssi -l usage --description 'display brief usage message.'

