# mysql_install_db
# Autogenerated from man page /usr/local/share/man/man1/mysql_install_db.1
# using Deroffing man parser
complete -c mysql_install_db -l user --description 'option to indicate the user name that mysqld will run as.'
complete -c mysql_install_db -l basedir --description 'or.'
complete -c mysql_install_db -l datadir --description 'if mysql_install_db does not use the correct lo… [See Man Page]'
complete -c mysql_install_db -l defaults-extra-file --description 'option when you run mysql_install_db.'
complete -c mysql_install_db -l help --description '.'
complete -c mysql_install_db -l builddir --description '.'
complete -c mysql_install_db -l srcdir --description 'and out-of-source builds.'
complete -c mysql_install_db -l cross-bootstrap --description '.'
complete -c mysql_install_db -l ldata --description '.'
complete -c mysql_install_db -l defaults-file --description '.'
complete -c mysql_install_db -l force --description '.'
complete -c mysql_install_db -l no-defaults --description '.'
complete -c mysql_install_db -l random-passwords --description '.'
complete -c mysql_install_db -l rpm --description '.'
complete -c mysql_install_db -l skip-name-resolve --description '.'
complete -c mysql_install_db -l verbose --description '.'
complete -c mysql_install_db -l windows --description '.'

