# pkd
# Autogenerated from man page /usr/share/man/man8/pkd.8
# using Darwin man parser
complete -c pkd -s d --description 'Use an alternate registry database file at the given location.'
complete -c pkd -s v --description 'Ask pkd to log more verbosely to the system log.'
complete -c pkd -s W --description 'Asks pkd to write the location of this user\'s P… [See Man Page]'

