# pluginkit
# Autogenerated from man page /usr/share/man/man8/pluginkit.8
# using Darwin man parser
complete -c pluginkit -s a --description 'Explicitly adds plugins at the file location(s) given.'
complete -c pluginkit -s l --description 'When matching plugins, requests only the latest… [See Man Page]'
complete -c pluginkit -s r --description 'Explicitly removes plugins at the file location(s) given.'
complete -c pluginkit -l raw --description 'Present replies from the management daemon (pkd… [See Man Page]'
complete -c pluginkit -s v --description 'Asks for more verbose operation.  \\" Ends the list Pp .'

