# postconf
# Autogenerated from man page /usr/share/man/man1/postconf.1
# using Deroffing man parser
complete -c postconf -s a --description 'List the available SASL server plug-in types.'
complete -c postconf -s A --description 'List the available SASL client plug-in types.'
complete -c postconf -s b --description 'Display the message text that appears at the be… [See Man Page]'
complete -c postconf -s c --description 'The main.'
complete -c postconf -s C --description 'When displaying main.'
complete -c postconf -s d --description 'Print main.'
complete -c postconf -s e --description 'Edit the main.'
complete -c postconf -s f --description 'Fold long lines when printing main. cf or master.'
complete -c postconf -s h --description 'Show main.'
complete -c postconf -s l --description 'List the names of all supported mailbox locking methods.'
complete -c postconf -s m --description 'List the names of all supported lookup table types.'
complete -c postconf -s M --description 'Show master. cf file contents instead of main.'
complete -c postconf -s n --description 'Print main.'
complete -c postconf -s t --description 'Display the templates for text that appears at … [See Man Page]'
complete -c postconf -s v --description 'Enable verbose logging for debugging purposes.'
complete -c postconf -s '#' --description 'Edit the main.'

