# powermetrics
# Autogenerated from man page /usr/share/man/man1/powermetrics.1
# using Darwin man parser
complete -c powermetrics -s h --description 'Print help message.'
complete -c powermetrics -s u --description 'Output to file instead of stdout.'
complete -c powermetrics -s b --description 'Set output buffer size (0=none, 1=line).'
complete -c powermetrics -s i --description 'sample every N ms (0=disabled) [default: 5000ms].'
complete -c powermetrics -s n --description 'Obtain N periodic samples (0=infinite) [default: 0].'
complete -c powermetrics -s t --description 'Assume package idle wakeups have a CPU time cos… [See Man Page]'
complete -c powermetrics -s o --description 'Order process list using specified method [defa… [See Man Page]'
complete -c powermetrics -s f --description 'Display data in specified format [default: text… [See Man Page]'
complete -c powermetrics -s a --description 'Display poweravg every N samples (0=disabled) [default: 10].'
complete -c powermetrics -l hide-platform-power --description 'Hide platform power data.'
complete -c powermetrics -l hide-cpu-duty-cycle --description 'Hide CPU duty cycle data.'
complete -c powermetrics -l hide-gpu-duty-cycle --description 'Hide GPU duty cycle data.'
complete -c powermetrics -l show-initial-usage --description 'Print initial sample for entire uptime.'
complete -c powermetrics -l show-usage-summary --description 'Print final usage summary when exiting El Pp Th… [See Man Page]'

