# ptargrep5
# Autogenerated from man page /usr/share/man/man1/ptargrep5.16.1
# using Type1
complete -c ptargrep5 -l basename -o 'b)' --description 'When matching files are extracted, ignore the d… [See Man Page]'
complete -c ptargrep5 -l ignore-case -o 'i)' --description 'Make pattern matching case-insensitive.'
complete -c ptargrep5 -l list-only -o 'l)' --description 'Print the pathname of each matching file from t… [See Man Page]'
complete -c ptargrep5 -l verbose -o 'v)' --description 'Log debugging info to \\s-1STDERR\\s0.'

