# security2
# Autogenerated from man page /usr/share/man/man1/security2.1
# using Darwin man parser
complete -c security2 -s a --description 'Description of -a flag.'
complete -c security2 -s b --description 'Description of -b flag \\" Ends the list Pp .'

