# symbols
# Autogenerated from man page /usr/share/man/man1/symbols.1.gz
# using Darwin man parser
complete -c symbols -o cpuTpe --description 'Specify the target architecture cpu type as a numeric value.'

