# sysdiagnose
# Autogenerated from man page /usr/share/man/man1/sysdiagnose.1
# using Darwin man parser
complete -c sysdiagnose -s h --description 'Print full usage.'
complete -c sysdiagnose -s f --description 'Specify the directory where the results will be stored.'
complete -c sysdiagnose -s q --description 'Skips calling footprint.'
complete -c sysdiagnose -s t --description 'Enable "Thorough Mode".  See below.'
complete -c sysdiagnose -s b --description 'Do not show the resulting archive in a Finder w… [See Man Page]'

