# taskpolicy
# Autogenerated from man page /usr/share/man/man8/taskpolicy.8
# using Darwin man parser
complete -c taskpolicy -s d --description 'Run the program after calling setiopolicy_np 3 … [See Man Page]'
complete -c taskpolicy -s g --description 'Run the program after calling setiopolicy_np 3 … [See Man Page]'
complete -c taskpolicy -s b --description 'Run the program after calling setpriority 2 wit… [See Man Page]'

