# tcamgr
# Autogenerated from man page /usr/local/share/man/man1/tcamgr.1
# using Deroffing man parser
complete -c tcamgr -o sx --description '.'
complete -c tcamgr -o sep --description '.'
complete -c tcamgr -o dk --description '.'
complete -c tcamgr -o dc --description '.'
complete -c tcamgr -o dai --description '.'
complete -c tcamgr -o dad --description '.'
complete -c tcamgr -o px --description '.'
complete -c tcamgr -o pz --description '.'
complete -c tcamgr -s m --description '.'
complete -c tcamgr -o pv --description '.'
complete -c tcamgr -o fm --description 'This command returns 0 on success, another on failure.'

