# tcbmttest
# Autogenerated from man page /usr/local/share/man/man1/tcbmttest.1
# using Deroffing man parser
complete -c tcbmttest -o tl --description '.'
complete -c tcbmttest -o td --description '.'
complete -c tcbmttest -o tb --description '.'
complete -c tcbmttest -o tt --description '.'
complete -c tcbmttest -o tx --description '.'
complete -c tcbmttest -o xm --description '.'
complete -c tcbmttest -o df --description '.'
complete -c tcbmttest -o nl --description '.'
complete -c tcbmttest -o nb --description '.'
complete -c tcbmttest -o rnd --description '.'
complete -c tcbmttest -o wb --description '.'
complete -c tcbmttest -o nc --description '.'
complete -c tcbmttest -o rr --description 'This command returns 0 on success, another on failure.'

