# tcfmttest
# Autogenerated from man page /usr/local/share/man/man1/tcfmttest.1
# using Deroffing man parser
complete -c tcfmttest -o nl --description '.'
complete -c tcfmttest -o nb --description '.'
complete -c tcfmttest -o rnd --description '.'
complete -c tcfmttest -o wb --description '.'
complete -c tcfmttest -o nc --description '.'
complete -c tcfmttest -o rr --description 'This command returns 0 on success, another on failure.'

