# tcfmgr
# Autogenerated from man page /usr/local/share/man/man1/tcfmgr.1
# using Deroffing man parser
complete -c tcfmgr -o nl --description '.'
complete -c tcfmgr -o nb --description '.'
complete -c tcfmgr -o sx --description '.'
complete -c tcfmgr -o dk --description '.'
complete -c tcfmgr -o dc --description '.'
complete -c tcfmgr -o dai --description '.'
complete -c tcfmgr -o dad --description '.'
complete -c tcfmgr -o px --description '.'
complete -c tcfmgr -o pz --description '.'
complete -c tcfmgr -s m --description '.'
complete -c tcfmgr -o pv --description '.'
complete -c tcfmgr -o rb --description '.'
complete -c tcfmgr -o ri --description '.'
complete -c tcfmgr -o sc --description 'This command returns 0 on success, another on failure.'

