# tcftest
# Autogenerated from man page /usr/local/share/man/man1/tcftest.1
# using Deroffing man parser
complete -c tcftest -o mt --description '.'
complete -c tcftest -o nl --description '.'
complete -c tcftest -o nb --description '.'
complete -c tcftest -o rnd --description '.'
complete -c tcftest -o wb --description '.'
complete -c tcftest -o pn --description '.'
complete -c tcftest -o dai --description '.'
complete -c tcftest -o dad --description '.'
complete -c tcftest -o rl --description 'This command returns 0 on success, another on failure.'

