# tchmgr
# Autogenerated from man page /usr/local/share/man/man1/tchmgr.1
# using Deroffing man parser
complete -c tchmgr -o tl --description '.'
complete -c tchmgr -o td --description '.'
complete -c tchmgr -o tb --description '.'
complete -c tchmgr -o tt --description '.'
complete -c tchmgr -o tx --description '.'
complete -c tchmgr -o nl --description '.'
complete -c tchmgr -o nb --description '.'
complete -c tchmgr -o sx --description '.'
complete -c tchmgr -o dk --description '.'
complete -c tchmgr -o dc --description '.'
complete -c tchmgr -o dai --description '.'
complete -c tchmgr -o dad --description '.'
complete -c tchmgr -o px --description '.'
complete -c tchmgr -o pz --description '.'
complete -c tchmgr -s m --description '.'
complete -c tchmgr -o pv --description '.'
complete -c tchmgr -o fm --description '.'
complete -c tchmgr -o tz --description '.'
complete -c tchmgr -o df --description '.'
complete -c tchmgr -o sc --description 'This command returns 0 on success, another on failure.'

