# tchmttest
# Autogenerated from man page /usr/local/share/man/man1/tchmttest.1
# using Deroffing man parser
complete -c tchmttest -o tl --description '.'
complete -c tchmttest -o td --description '.'
complete -c tchmttest -o tb --description '.'
complete -c tchmttest -o tt --description '.'
complete -c tchmttest -o tx --description '.'
complete -c tchmttest -o rc --description '.'
complete -c tchmttest -o xm --description '.'
complete -c tchmttest -o df --description '.'
complete -c tchmttest -o nl --description '.'
complete -c tchmttest -o nb --description '.'
complete -c tchmttest -o as --description '.'
complete -c tchmttest -o rnd --description '.'
complete -c tchmttest -o wb --description '.'
complete -c tchmttest -o nc --description '.'
complete -c tchmttest -o rr --description 'This command returns 0 on success, another on failure.'

