# tchtest
# Autogenerated from man page /usr/local/share/man/man1/tchtest.1
# using Deroffing man parser
complete -c tchtest -o mt --description '.'
complete -c tchtest -o tl --description '.'
complete -c tchtest -o td --description '.'
complete -c tchtest -o tb --description '.'
complete -c tchtest -o tt --description '.'
complete -c tchtest -o tx --description '.'
complete -c tchtest -o rc --description '.'
complete -c tchtest -o xm --description '.'
complete -c tchtest -o df --description '.'
complete -c tchtest -o nl --description '.'
complete -c tchtest -o nb --description '.'
complete -c tchtest -o as --description '.'
complete -c tchtest -o rnd --description '.'
complete -c tchtest -o wb --description '.'
complete -c tchtest -o pn --description '.'
complete -c tchtest -o dai --description '.'
complete -c tchtest -o dad --description '.'
complete -c tchtest -o rl --description '.'
complete -c tchtest -o ru --description 'This command returns 0 on success, another on failure.'

