# tctmttest
# Autogenerated from man page /usr/local/share/man/man1/tctmttest.1
# using Deroffing man parser
complete -c tctmttest -o tl --description '.'
complete -c tctmttest -o td --description '.'
complete -c tctmttest -o tb --description '.'
complete -c tctmttest -o tt --description '.'
complete -c tctmttest -o tx --description '.'
complete -c tctmttest -o rc --description '.'
complete -c tctmttest -o lc --description '.'
complete -c tctmttest -o nc --description '.'
complete -c tctmttest -o xm --description '.'
complete -c tctmttest -o df --description '.'
complete -c tctmttest -o ip --description '.'
complete -c tctmttest -o is --description '.'
complete -c tctmttest -o in --description '.'
complete -c tctmttest -o it --description '.'
complete -c tctmttest -o if --description '.'
complete -c tctmttest -o ix --description '.'
complete -c tctmttest -o nl --description '.'
complete -c tctmttest -o nb --description '.'
complete -c tctmttest -o rnd --description '.'
complete -c tctmttest -o rr --description 'This command returns 0 on success, another on failure.'

