# tcumttest
# Autogenerated from man page /usr/local/share/man/man1/tcumttest.1
# using Deroffing man parser
complete -c tcumttest -o rnd --description '.'
complete -c tcumttest -o nc --description '.'
complete -c tcumttest -o rr --description 'This command returns 0 on success, another on failure.'

