# tcutest
# Autogenerated from man page /usr/local/share/man/man1/tcutest.1
# using Deroffing man parser
complete -c tcutest -o rd --description '.'
complete -c tcutest -o tr --description '.'
complete -c tcutest -o rnd --description '.'
complete -c tcutest -o dk --description '.'
complete -c tcutest -o dc --description '.'
complete -c tcutest -o dai --description '.'
complete -c tcutest -o dad --description '.'
complete -c tcutest -o dpr --description 'This command returns 0 on success, another on failure.'

