# wakeonlan
# Autogenerated from man page /usr/local/share/man/man1/wakeonlan.1
# using Type1
complete -c wakeonlan -s h --description 'Displays the help information.'
complete -c wakeonlan -s v --description 'Displays the script version.'
complete -c wakeonlan -s i --description 'Destination \\s-1IP\\s0 address.'
complete -c wakeonlan -s p --description 'Destination port.  Default: 9 (the discard port).'

