# xapian-inspect
# Autogenerated from man page /usr/local/share/man/man1/xapian-inspect.1
# using Deroffing man parser
complete -c xapian-inspect -l help --description 'display this help and exit.'
complete -c xapian-inspect -l version --description 'output version information and exit.'

