# xbssnapshot
# Autogenerated from man page /usr/share/man/man1/xbssnapshot.1
# using Type1
complete -c xbssnapshot -l live --description 'Force xbssnapshot to bypass the snapshot cache … [See Man Page]'
complete -c xbssnapshot -l nolive --description 'Force xbssnapshot to not fetch data from Cortex… [See Man Page]'
complete -c xbssnapshot -l age --description 'When considering if a snapshot found in the sna… [See Man Page]'
complete -c xbssnapshot -l xpc --description 'Use XPC service when fetching data from Cortex.'
complete -c xbssnapshot -l noxpc --description 'Bypass XPC service when fetching data from Cortex.'

