# xsanadmin
# Autogenerated from man page /usr/share/man/man8/xsanadmin.8
# using Darwin man parser
complete -c xsanadmin -s d --description '--debug Print command to the terminal.  Pp.'
complete -c xsanadmin -s h --description '--help Print usage summary and exit.  Pp.'
complete -c xsanadmin -s v --description '--version Print build version and exit.  Pp.'
complete -c xsanadmin -s x --description '--xml Generate output as XML instead of key-value pairs.'

